<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Producto;
use App\Models\Categoria;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
       $productos = [
            [
                'nombre' => 'Liquid Foundation',
                'descripcion' => 'Light Medium Warm',
                'precio' => 55000,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base1.webp',
                'stock' => 20,
            ],
            [
                'nombre' => 'Liquid Foundation',
                'descripcion' => 'Deep Neutral',
                'precio' => 55000,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base2.webp',
                'stock' => 80,
            ],
            [
                'nombre' => 'Liquid Foundation',
                'descripcion' => 'Medium Deep Neutral',
                'precio' => 55000,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base3.webp',
                'stock' => 50,
            ],
            [
                'nombre' => 'Liquid Foundation',
                'descripcion' => 'Fair Warm',
                'precio' => 55000,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base4.webp',
                'stock' => 10,
            ],
            [
                'nombre' => 'Liquid Foundation',
                'descripcion' => 'Deep Warm',
                'precio' => 55000,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base5.webp',
                'stock' => 20,
            ],
            [
                'nombre' => 'Skin Tint Base',
                'descripcion' => 'Fair Warm',
                'precio' => 48900,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base6.webp',
                'stock' => 38,
            ],
            [
                'nombre' => 'Skin Tint Base',
                'descripcion' => 'Light Cool Pink',
                'precio' => 48900,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base7.webp',
                'stock' => 25,
            ],
            [
                'nombre' => 'Skin Tint Base',
                'descripcion' => 'Medium Cool Peach',
                'precio' => 48900,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base8.webp',
                'stock' => 10,
            ],
            [
                'nombre' => 'Skin Tint Base',
                'descripcion' => 'Deep Warm Golden',
                'precio' => 48900,
                'categoria' => 'bases',
                'imagen' => 'img/Prod-bases/base9.webp',
                'stock' => 30,
            ],

        // --- CORRECTORES ---
            [
                'nombre' => 'Fix Concealer',
                'descripcion' => 'Light Tone',
                'precio' => 30500,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector1.webp',
                'stock' => 10,
                
            ],
            [
                'nombre' => 'Fix Concealer',
                'descripcion' => 'Medium Tone',
                'precio' => 30500,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector2.webp',
                'stock' => 30,
            ],
            [
                'nombre' => 'Fix Concealer',
                'descripcion' => 'Neutral Tone',
                'precio' => 30500,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector3.webp',
                'stock' => 15,
            ],
            [
                'nombre' => 'Fix Concealer',
                'descripcion' => 'Medium Deep Neutral Tone',
                'precio' => 30500,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector4.webp',
                'stock' => 22,
            ],
            [
                'nombre' => 'Fix Concealer',
                'descripcion' => 'Deep Neutral Tone',
                'precio' => 30500,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector5.webp',
                'stock' => 9,
            ],
            [
                'nombre' => 'Creamy Camouflage',
                'descripcion' => 'Peach Tone',
                'precio' => 22000,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector6.webp',
                'stock' => 5,
            ],
            [
                'nombre' => 'Creamy Camouflage',
                'descripcion' => 'Medium Tone',
                'precio' => 22000,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector7.webp',
                'stock' => 7,
            ],
            [
                'nombre' => 'Creamy Camouflage',
                'descripcion' => 'Deep Neutral Tone',
                'precio' => 22000,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector8.webp',
                'stock' => 17,
            ],
            [
                'nombre' => 'Creamy Camouflage',
                'descripcion' => 'Deep Warm Tone',
                'precio' => 22000,
                'categoria' => 'correctores',
                'imagen' => 'img/Prod-correctores/corrector9.webp',
                'stock' => 20,
            ],

            // --- ILUMINADORES ---
            [
                'nombre' => 'Reflection Highlighter',
                'descripcion' => '-',
                'precio' => 15000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador9.webp',
                'stock' => 22,
            ],
            [
                'nombre' => 'Pinkish highlighter',
                'descripcion' => '-',
                'precio' => 15000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador5.webp',
                'stock' => 30,
            ],
            [
                'nombre' => 'Glowy Pink Highlighter',
                'descripcion' => '-',
                'precio' => 15000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador6.webp',
                'stock' => 13,
            ],
            [
                'nombre' => 'Golden Peach Highlighter',
                'descripcion' => '-',
                'precio' => 15000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador7.webp',
                'stock' => 21,
            ],
            [
                'nombre' => 'Golden Hour Highlighter',
                'descripcion' => '-',
                'precio' => 15000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador8.webp',
                'stock' => 33,
            ],
            [
                'nombre' => 'Silver Shine Pop',
                'descripcion' => '-',
                'precio' => 23000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador3.webp',
                'stock' => 8,
            ],
            [
                'nombre' => 'Soft Pink Pop',
                'descripcion' => '-',
                'precio' => 23000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador12.webp',
                'stock' => 6,
            ],
            [
                'nombre' => 'Golden Pop',
                'descripcion' => '-',
                'precio' => 23000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador13.webp',
                'stock' => 18,
            ],
            [
                'nombre' => 'Golden Coral Pop',
                'descripcion' => '-',
                'precio' => 23000,
                'categoria' => 'iluminadores',
                'imagen' => 'img/Prod-Iluminador/iluminador14.webp',
                'stock' => 29,
            ],
            // --- LABIALES ---
            [
                'nombre' => 'Dewy Dream Balm',
                'descripcion' => '-',
                'precio' => 28900,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab6.webp',
                'stock' => 10,
            ],
            [
                'nombre' => 'Hope Balm',
                'descripcion' => '-',
                'precio' => 28900,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab8.webp',
                'stock' => 16,
            ],
            [
                'nombre' => 'Matte Fearless Balm',
                'descripcion' => '-',
                'precio' => 28900,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab10.webp',
                'stock' => 15,
            ],
            [
                'nombre' => 'Stay Vulnerable Read Balm',
                'descripcion' => '-',
                'precio' => 28900,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab11.webp',
                'stock' => 20,
            ],
            [
                'nombre' => 'Pinch Rose Lipstick',
                'descripcion' => '-',
                'precio' => 35500,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab5.webp',
                'stock' => 24,
            ],
            [
                'nombre' => 'Wine Glaze Lipstick',
                'descripcion' => '-',
                'precio' => 35500,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab12.webp',
                'stock' => 4,
            ],
            [
                'nombre' => 'Brave Almond Lipstick',
                'descripcion' => '-',
                'precio' => 35500,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab13.webp',
                'stock' => 4,
            ],
            [
                'nombre' => 'Intense Velvet Lip Balm',
                'descripcion' => '-',
                'precio' => 30000,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab14.webp',
                'stock' => 26,
            ],
            [
                'nombre' => 'Sweet Purplish Lip Balm',
                'descripcion' => '-',
                'precio' => 30000,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab15.webp',
                'stock' => 22,
            ],
            [
                'nombre' => 'Pure Shine Gloss',
                'descripcion' => '-',
                'precio' => 24000,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab16.webp',
                'stock' => 30,
            ],
            [
                'nombre' => 'Love Energy Gloss',
                'descripcion' => '-',
                'precio' => 24000,
                'categoria' => 'labiales',
                'imagen' => 'img/Prod-Labiales/lab17.webp',
                'stock' => 14,
            ],
            // --- POLVOS ---
            [
                'nombre' => 'Matte Finish Powder',
                'descripcion' => 'Light Medium',
                'precio' => 12500,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvo1.webp',
                'stock' => 15,
            ],
            [
                'nombre' => 'Matte Finish Powder',
                'descripcion' => 'Fair Neutral',
                'precio' => 12500,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvo2.webp',
                'stock' => 5,
            ],
            [
                'nombre' => 'Matte Finish Powder',
                'descripcion' => 'Medium Neutral',
                'precio' => 12500,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvo3.webp',
                'stock' => 20,
            ],
            [
                'nombre' => 'Matte Finish Powder',
                'descripcion' => 'Medium Deep',
                'precio' => 12500,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvo4.webp',
                'stock' => 25,
            ],
            [
                'nombre' => 'Matte Finish Powder',
                'descripcion' => 'Deep Neutral',
                'precio' => 12500,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvo5.webp',
                'stock' => 23,
            ],
            [
                'nombre' => 'Velvet Touch Compact',
                'descripcion' => 'Traslucent',
                'precio' => 21500,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvo6.webp',
                'stock' => 17,
            ],
            [
                'nombre' => 'Velvet Touch Compact',
                'descripcion' => 'Medium Deep',
                'precio' => 21500,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvo7.webp',
                'stock' => 4,
            ],
            [
                'nombre' => 'Velvet Touch Compact',
                'descripcion' => 'Deep Warm',
                'precio' => 21500,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvo8.webp',
                'stock' => 6,
            ],
            [
                'nombre' => 'Radiant Sun Bronzing',
                'descripcion' => '-',
                'precio' => 20400,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvoBronzer.webp',
                'stock' => 9,
            ],
            [
                'nombre' => 'Radiant Sun Bronzing 2',
                'descripcion' => '-',
                'precio' => 20400,
                'categoria' => 'polvos',
                'imagen' => 'img/Prod-polvos/polvoBronzer2.webp',
                'stock' => 10,
            ],
            // --- RUBORES ---
            [
                'nombre' => 'Soft Pinch Blush',
                'descripcion' => '-',
                'precio' => 30500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor1.webp',
                'stock' => 30,
            ],
            [
                'nombre' => 'Day&Day Happy Blush',
                'descripcion' => '-',
                'precio' => 19500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor2.webp',
                'stock' => 23,
            ],
            [
                'nombre' => 'Luminous Pink Blush',
                'descripcion' => '-',
                'precio' => 19500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor6.webp',
                'stock' => 18,
            ],
            [
                'nombre' => 'Graceful Mauve Blush',
                'descripcion' => '-',
                'precio' => 19500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor7.webp',
                'stock' => 19,
            ],
            [
                'nombre' => 'Encourage Soft Blush',
                'descripcion' => '-',
                'precio' => 19500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor8.webp',
                'stock' => 10,
            ],
            [
                'nombre' => 'True Almond Blush',
                'descripcion' => '-',
                'precio' => 19500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor9.webp',
                'stock' => 25,
            ],
            [
                'nombre' => 'Peachy Glow Blush',
                'descripcion' => '-',
                'precio' => 19500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor10.webp',
                'stock' => 30,
            ],
            [
                'nombre' => 'Lucky Pink Blush',
                'descripcion' => '-',
                'precio' => 19500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor11.webp',
                'stock' => 22,
            ],
            [
                'nombre' => 'Deep Verbena Blush',
                'descripcion' => '-',
                'precio' => 19500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor12.webp',
                'stock' => 12,
            ],
            [
                'nombre' => 'Cherish Liquid Blush',
                'descripcion' => '-',
                'precio' => 25500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor13.webp',
                'stock' => 9,
            ],
            [
                'nombre' => 'Aura Signature Liquid Blush',
                'descripcion' => '-',
                'precio' => 25500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor15.webp',
                'stock' => 5,
            ],
            [
                'nombre' => 'Golden Glow Liquid Blush',
                'descripcion' => '-',
                'precio' => 25500,
                'categoria' => 'rubores',
                'imagen' => 'img/Prod-Rubores/rubor.webp',
                'stock' => 15,
            ]
        
        ];
        
        foreach ($productos as $item) {
            $categoria = Categoria::where('slug', $item['categoria'])->first();

            if ($categoria) {
                Producto::create([
                    'nombre'      => $item['nombre'],
                    'descripcion' => $item['descripcion'],
                    'precio'      => $item['precio'],
                    'imagen'      => $item['imagen'],
                    'stock'       => $item['stock'] ?? 0,
                    'categoria_id'=> $categoria->id, 
                ]);
            }
        }
    }
}
